# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "89bd9b490b011c4fbdf1de932d9b9c74"
name = "outfitplaner-hesam"
handle = "outfitplanenrhesam"
application_url = "https://winners-gpl-cheque-code.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hesams-outfitplanner.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://winners-gpl-cheque-code.trycloudflare.com/auth/callback",
  "https://winners-gpl-cheque-code.trycloudflare.com/auth/shopify/callback",
  "https://winners-gpl-cheque-code.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
