# Helm Chart Default Values

replicaCount: 1

image:
  # Full image tag, including repository.
  # This is required, but set by the Github Action to the image tag passed in there.
  #fullTag: 
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

# This controls the app configuration.
# You can either pass in environment variables, which will be stored
# in a K8s secret and then mounted via envFrom and/or you can
# provide a list of file secrets which will be mounted into the pods
#
# Please note that you need to create these secrets yourself, or rather
# the Github Action will take care of that for you (secret-files).
appConfiguration:
  envsSecretName: shopify-app-env
  envs: {}
    # HOST: ...
    # SCOPES: ...
    # SHOPIFY_APP_ID: ...
  files:
    # - mountAt: /app/foobar.json
    #   secretName: ...


restartPolicy: Always

# One PVC for app storage, you can add your own volumes!
storagePvc:
  enabled: true
  name: shopify-app-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ki

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ports: {}
  # - name: http
  #   containerPort: 80
  #   protocol: TCP

livenessProbe:
  exec:
    command:
      # Check if the nfs storage is mounted
      - ls
      - /app/storage
    initialDelaySeconds: 15
    periodSeconds: 5

readinessProbe: {}
  # httpGet:
  #   path: /
  #   port: http

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
